# Generated by Django 3.2.5 on 2021-07-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=12)),
                ('second_name', models.CharField(max_length=13)),
                ('age', models.PositiveSmallIntegerField(max_length=3)),
                ('date', models.DateField(max_length=10)),
            ],
        ),
    ]
